# Clash as Transparent proxy gateway via TPROXY
tproxy: false

# RESTful web API listening address
external-controller: 192.168.50.1:9090

proxies:
# 更多协议配置示例：https://github.com/Dreamacro/clash/wiki/configuration

  # VMess
  - { name: "US-Ashburn-01", type: vmess, server: server, port: 443, uuid: uuid, alterId: 0, cipher: auto }
  - { name: "JP-Tokyo-02", type: vmess, server: server, port: 443, uuid: uuid, alterId: 0, cipher: auto }

proxy-groups:
# url-test select which proxy will be used by benchmarking speed to a URL.
- name: "UrlTest"
  type: url-test
  proxies:
    - "US-Ashburn-01"
    - "JP-Tokyo-02"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300

# fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
- name: "Fallback"
  type: fallback
  proxies:
    - "UrlTest"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300

# select is used for selecting proxy or proxy group
# you can use RESTful API to switch proxy is recommended for use in GUI.
- name: "PROXY"
  type: select
  proxies:
    - "UrlTest"

# 白名单模式 PROXY，黑名单模式 DIRECT
- name: "MATCH"
  type: select
  proxies:
    - "PROXY"
    - "DIRECT"

# Apple 服务代理
- name: "Apple"
  type: select
  proxies:
    - "DIRECT"
    - "PROXY"

# 国际流媒体服务
- name: "GlobalMedia"
  type: select
  proxies:
    - "PROXY"

# 大陆流媒体面向港澳台限定服务
- name: "HKMTMedia"
  type: select
  proxies:
    - "UrlTest"

# 运营商及声名狼藉网站劫持
- name: "Hijacking"
  type: select
  proxies:
    - "REJECT"
    - "DIRECT"

