# 本地局域网地址
- name: "Lan"
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/Clash/Lan/Lan.yaml"

# 反劫持
- name: "Hijacking"
  group: "Hijacking"
  ruleset: "rules/blackmatrix7/Clash/Hijacking/Hijacking.yaml"

# ChinaMedia
- name: "ChinaMedia" 
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/Clash/ChinaMedia/ChinaMedia.yaml"

# China
- name: "China" 
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/Clash/China/China.yaml"

# AsianMedia
- name: "AsianMedia" 
  group: "DIRECT"
  ruleset: "rules/blackmatrix7/Clash/AsianMedia/AsianMedia.yaml"

# Apple
- name: "Apple" 
  group: "Apple"
  ruleset: "rules/blackmatrix7/Clash/Apple/Apple.yaml"

# Facebook
- name: "Facebook"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Clash/Facebook/Facebook.yaml"

# Twitter
- name: "Twitter"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Clash/Twitter/Twitter.yaml"

# Google
- name: "Google"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Clash/Google/Google.yaml"

# OneDrive
- name: "OneDrive"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Clash/OneDrive/OneDrive.yaml"

# Telegram
- name: "Telegram"
  group: "Proxy"
  ruleset: "rules/blackmatrix7/Clash/Telegram/Telegram.yaml"

# Speedtest
- name: "Speedtest"
  group: "Speedtest"
  ruleset: "rules/blackmatrix7/Clash/Speedtest/Speedtest.yaml"

# GlobalMedia
- name: "GlobalMedia"
  group: "GlobalMedia"
  ruleset: "rules/blackmatrix7/Clash/GlobalMedia/GlobalMedia.yaml"